language: python

dist: bionic

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.8
      env: TOXENV=pep8

install:
  pip install tox

script:
  tox

notifications:
  email: false
